language: en
navbar:
  blog_title: 'FearTheOldBlood'
  menu:
    - { key: 'Home', link: '/', icon: 'iconfont icon-home-fill', name: 'Home' }
    - { key: 'About 0xvoidw', link: '/about/', icon: 'iconfont icon-user-fill', name: 'About' }
    - { key: 'InfraAcCode', link: '/iac/', icon: 'iconfont icon-code', name: 'InfraAsCode' }
    - { key: 'Book Reviews', link: '/book-reviews/', icon: 'iconfont icon-book', name: 'Book Reviews' }

dark_mode:
  enabled: true
  default: auto
