name: Run a spotify script & deploy results to Feartheoldblood.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/spotify.sh
    env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_SECRET_KEY }}
# deploy:
#   type: git
#   repo: git@github.com:yrpang/yrpang.github.io.git
#   branch: master